IMAGE_WIDTH=128
IMAGE_HEIGHT=128
BUFFER_SIZE=2000
NUM_TRAIN=21000
BATCH_SIZE=64
DIRECTORY_DATASET="../dataset/dataset/"
DIRECTORY_DATASET_SEPERATED='../dataset/dataset_seperated/'

IDX_TO_LABELS = {0: 'cat', 1: 'dog'}